version: 1.8.0.{build}

before_build:
    - nuget restore Loyc-Slim.sln

build_script:
    # First, set some environment variables.
    # SEMVER is set manually. Not sure how this can be automated.
    - set SEMVER=1.8.0
    - echo %APPVEYOR_REPO_TAG%
    # Build packages as SEMVER-ci{build}
    - ps: if ($env:APPVEYOR_REPO_TAG -eq $True) { $env:PKG_VERSION = $env:SEMVER; } else { $env:PKG_VERSION = "$($env:SEMVER)-ci$($env:APPVEYOR_BUILD_NUMBER)"; }
    - echo %PKG_VERSION%

    # Build the Loyc libraries in release mode, for all possible configurations.
    - msbuild /p:Configuration=Release.NET45 Loyc-Slim.sln
    - msbuild /p:Configuration=Release.NET4 Loyc-Slim.sln
    - msbuild /p:Configuration=Release.NET35 Loyc-Slim.sln

after_build:
    # Package the LoycCore libraries
    - nuget pack -Version %PKG_VERSION% Core\LoycCore.nuspec
    # Package ends up in LoycCore.$SEMVER.nupkg

test_script:
    # Unfortunately, some tests are still broken.
    - Bin\Release.NET45\Tests.exe 1
    - Bin\Release.NET45\Tests.exe 2
    - Bin\Release.NET45\Tests.exe 7
    - Bin\Release.NET45\Tests.exe 8

assembly_info:
    patch: true
    file: AssemblyVersion.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

artifacts:
    - path: '*.nupkg'
      name: nupkgs

# Uncomment the section below to push the NuGet
# package whenever a git tag is pushed.
#deploy:
#    - provider: NuGet
#      server:
#      api_key:
#          secure: Encrypted key goes here. Use https://ci.appveyor.com/tools/encrypt to encrypt your NuGet API key.
#      skip_symbols: true
#      artifact: /.*\.nupkg/
#      on:
#          branch: master # Release from master branch only.
#          appveyor_repo_tag: true # Deploy on tag push only.
